<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SmallCategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('small_categories')->truncate();

        DB::table('small_categories')->insert([
            [
                'name' => 'トップス',
                'slug' => 'tops',
                'description' => 'トップス',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 1,
            ],
            [
                'name' => 'ボトムス',
                'slug' => 'bottoms',
                'description' => 'ボトムス',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 1,
            ],
            [
                'name' => 'ドレス',
                'slug' => 'dress',
                'description' => 'ドレス',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 1,
            ],
            [
                'name' => 'アクセサリー（ジュエリー、バッグ、スカーフなど）',
                'slug' => 'accessories',
                'description' => 'アクセサリー（ジュエリー、バッグ、スカーフなど）',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 1,
            ],
            [
                'name' => '靴',
                'slug' => 'shoes',
                'description' => '靴',
                'image' => '',
                'sort' => 5,
                'sub_category_id' => 1,
            ],
            [
                'name' => 'アウター',
                'slug' => 'outer',
                'description' => 'アウター',
                'image' => '',
                'sort' => 6,
                'sub_category_id' => 1,
            ],

            [
                'name' => 'スキンケア',
                'slug' => 'skincare',
                'description' => 'スキンケア',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 2,
            ],
            [
                'name' => 'メイクアップ',
                'slug' => 'makeup',
                'description' => 'メイクアップ',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 2,
            ],
            [
                'name' => 'ヘアケア',
                'slug' => 'haircare',
                'description' => 'ヘアケア',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 2,
            ],
            [
                'name' => '香水',
                'slug' => 'perfume',
                'description' => '香水',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 2,
            ],
            [
                'name' => 'ネイルケア',
                'slug' => 'nailcare',
                'description' => 'ネイルケア',
                'image' => '',
                'sort' => 5,
                'sub_category_id' => 2,
            ],

            [
                'name' => 'サプリメント',
                'slug' => 'supplement',
                'description' => 'サプリメント',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 3,
            ],
            [
                'name' => 'フィットネス用品',
                'slug' => 'fitness',
                'description' => 'フィットネス用品',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 3,
            ],
            [
                'name' => '美容機器（フェイスマスク、美顔器など）',
                'slug' => 'beauty-machine',
                'description' => '美容機器（フェイスマスク、美顔器など）',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 3,
            ],

            [
                'name' => 'キッチン用品',
                'slug' => 'kitchen',
                'description' => 'キッチン用品',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 4,
            ],
            [
                'name' => 'バス・トイレ用品',
                'slug' => 'bathroom',
                'description' => 'バス・トイレ用品',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 4,
            ],
            [
                'name' => 'ベッド・寝具',
                'slug' => 'bed',
                'description' => 'ベッド・寝具',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 4,
            ],

            [
                'name' => 'ガジェット（スマートフォン、タブレットなど）',
                'slug' => 'gadget',
                'description' => 'ガジェット（スマートフォン、タブレットなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 5,
            ],
            [
                'name' => 'オーディオ機器（ヘッドフォン、スピーカーなど）',
                'slug' => 'audio',
                'description' => 'オーディオ機器（ヘッドフォン、スピーカーなど）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 5,
            ],

            [
                'name' => '書籍',
                'slug' => 'book',
                'description' => '書籍',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 6,
            ],
            [
                'name' => '映画・音楽',
                'slug' => 'movie',
                'description' => '映画・音楽',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 6,
            ],
            [
                'name' => 'アート・クラフト用品',
                'slug' => 'art',
                'description' => 'アート・クラフト用品',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 6,
            ],

            [
                'name' => 'マタニティウェア',
                'slug' => 'maternity',
                'description' => 'マタニティウェア',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 7,
            ],
            [
                'name' => 'ベビー服',
                'slug' => 'baby',
                'description' => 'ベビー服',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 7,
            ],
            [
                'name' => '授乳・食事用品',
                'slug' => 'feeding',
                'description' => '授乳・食事用品',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 7,
            ],
            [
                'name' => 'おむつ・おしりふき',
                'slug' => 'diaper',
                'description' => 'おむつ・おしりふき',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 7,
            ],

            [
                'name' => 'トップス（シャツ、Tシャツ、ポロシャツなど）',
                'slug' => 'tops',
                'description' => 'トップス（シャツ、Tシャツ、ポロシャツなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 8,
            ],
            [
                'name' => 'ボトムス（ジーンズ、スラックス、ショートパンツなど）',
                'slug' => 'bottoms',
                'description' => 'ボトムス（ジーンズ、スラックス、ショートパンツなど）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 8,
            ],
            [
                'name' => 'アウター（ジャケット、コート、パーカーなど）',
                'slug' => 'outer',
                'description' => 'アウター（ジャケット、コート、パーカーなど）',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 8,
            ],
            [
                'name' => '靴（スニーカー、ビジネスシューズ、ブーツなど）',
                'slug' => 'shoes',
                'description' => '靴（スニーカー、ビジネスシューズ、ブーツなど）',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 8,
            ],
            [
                'name' => 'アクセサリー（ベルト、財布、時計など）',
                'slug' => 'accessories',
                'description' => 'アクセサリー（ベルト、財布、時計など）',
                'image' => '',
                'sort' => 5,
                'sub_category_id' => 8,
            ],

            [
                'name' => 'スキンケア（洗顔料、ローションなど）',
                'slug' => 'skincare',
                'description' => 'スキンケア（洗顔料、ローションなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 9,
            ],
            [
                'name' => 'ヘアケア（シャンプー、コンディショナー、スタイリング製品など）',
                'slug' => 'haircare',
                'description' => 'ヘアケア（シャンプー、コンディショナー、スタイリング製品など）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 9,
            ],
            [
                'name' => '香水・デオドラント',
                'slug' => 'perfume',
                'description' => '香水・デオドラント',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 9,
            ],
            [
                'name' => 'シェービング用品',
                'slug' => 'shaving',
                'description' => 'シェービング用品',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 9,
            ],

            [
                'name' => 'スポーツウェア',
                'slug' => 'sportswear',
                'description' => 'スポーツウェア',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 10,
            ],
            [
                'name' => 'フィットネス機器',
                'slug' => 'fitness',
                'description' => 'フィットネス機器',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 10,
            ],
            [
                'name' => 'サプリメント',
                'slug' => 'supplement',
                'description' => 'サプリメント',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 10,
            ],

            [
                'name' => 'ガジェット（スマートフォン、スマートウォッチなど）',
                'slug' => 'gadget',
                'description' => 'ガジェット（スマートフォン、スマートウォッチなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 11,
            ],
            [
                'name' => 'オーディオ機器（ヘッドフォン、イヤフォン、スピーカーなど）',
                'slug' => 'audio',
                'description' => 'オーディオ機器（ヘッドフォン、イヤフォン、スピーカーなど）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 11,
            ],

            [
                'name' => '書籍・雑誌',
                'slug' => 'book',
                'description' => '書籍・雑誌',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 12,
            ],
            [
                'name' => 'ゲーム・ゲーム機',
                'slug' => 'game',
                'description' => 'ゲーム・ゲーム機',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 12,
            ],
            [
                'name' => 'スポーツ用品（ゴルフクラブ、釣り具など）',
                'slug' => 'sport',
                'description' => 'スポーツ用品（ゴルフクラブ、釣り具など）',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 12,
            ],

            [
                'name' => '自動車用品（タイヤ、カーオーディオなど）',
                'slug' => 'car',
                'description' => '自動車用品（タイヤ、カーオーディオなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 13,
            ],
            [
                'name' => 'バイク用品（ヘルメット、グローブなど）',
                'slug' => 'bike',
                'description' => 'バイク用品（ヘルメット、グローブなど）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 13,
            ],

            [
                'name' => 'キッチン用品（コーヒーメーカー、包丁など）',
                'slug' => 'kitchen',
                'description' => 'キッチン用品（コーヒーメーカー、包丁など）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 14,
            ],
            [
                'name' => 'インテリア（家具、照明など）',
                'slug' => 'interior',
                'description' => 'インテリア（家具、照明など）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 14,
            ],

            [
                'name' => 'トップス（Tシャツ、シャツ、ブラウスなど）',
                'slug' => 'tops',
                'description' => 'トップス（Tシャツ、シャツ、ブラウスなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 15,
            ],
            [
                'name' => 'ボトムス（パンツ、スカート、レギンスなど）',
                'slug' => 'bottoms',
                'description' => 'ボトムス（パンツ、スカート、レギンスなど）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 15,
            ],
            [
                'name' => 'アウター（ジャケット、コート、パーカーなど）',
                'slug' => 'bottoms',
                'description' => 'アウター（ジャケット、コート、パーカーなど）',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 15,
            ],
            [
                'name' => '下着・パジャマ',
                'slug' => 'bottoms',
                'description' => '下着・パジャマ',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 15,
            ],
            [
                'name' => '靴（スニーカー、サンダル、ブーツなど）',
                'slug' => 'shoes',
                'description' => '靴（スニーカー、サンダル、ブーツなど）',
                'image' => '',
                'sort' => 5,
                'sub_category_id' => 15,
            ],
            [
                'name' => 'アクセサリー（帽子、リュック、ヘアバンドなど）',
                'slug' => 'accessories',
                'description' => 'アクセサリー（帽子、リュック、ヘアバンドなど）',
                'image' => '',
                'sort' => 6,
                'sub_category_id' => 15,
            ],

            [
                'name' => '教育的なおもちゃ（ブロック、パズルなど）',
                'slug' => 'toy',
                'description' => '教育的なおもちゃ（ブロック、パズルなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 16,
            ],
            [
                'name' => 'アクションフィギュア・人形',
                'slug' => 'doll',
                'description' => 'アクションフィギュア・人形',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 16,
            ],
            [
                'name' => 'ゲーム（ボードゲーム、カードゲームなど）',
                'slug' => 'game',
                'description' => 'ゲーム（ボードゲーム、カードゲームなど）',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 16,
            ],
            [
                'name' => '屋外で遊ぶためのおもちゃ（バイク、三輪車、ボールなど）',
                'slug' => 'outdoor-toy',
                'description' => '屋外で遊ぶためのおもちゃ（バイク、三輪車、ボールなど）',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 16,
            ],

            [
                'name' => '学習用品（筆箱、ノート、鉛筆など）',
                'slug' => 'study',
                'description' => '学習用品（筆箱、ノート、鉛筆など）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 17,
            ],
            [
                'name' => '教育ソフトウェア・アプリ',
                'slug' => 'software',
                'description' => '教育ソフトウェア・アプリ',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 17,
            ],
            [
                'name' => '教育書籍・参考書',
                'slug' => 'book',
                'description' => '教育書籍・参考書',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 17,
            ],

            [
                'name' => 'スポーツ用品（バッグ、シューズ、ユニフォームなど）',
                'slug' => 'sport',
                'description' => 'スポーツ用品（バッグ、シューズ、ユニフォームなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 18,
            ],
            [
                'name' => 'アウトドア用品（テント、ランタン、寝袋など）',
                'slug' => 'outdoor',
                'description' => 'アウトドア用品（テント、ランタン、寝袋など）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 18,
            ],

            [
                'name' => 'ベビーケア（おむつ、哺乳瓶、ベビーフードなど）',
                'slug' => 'baby',
                'description' => 'ベビーケア（おむつ、哺乳瓶、ベビーフードなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 19,
            ],
            [
                'name' => '保健用品（歯ブラシ、シャンプー、ボディーソープなど）',
                'slug' => 'health',
                'description' => '保健用品（歯ブラシ、シャンプー、ボディーソープなど）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 19,
            ],

            [
                'name' => 'おやつ（クッキー、チョコレート、ジュースなど）',
                'slug' => 'snack',
                'description' => 'おやつ（クッキー、チョコレート、ジュースなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 20,
            ],
            [
                'name' => '健康食品（オーガニックスナック、フルーツバーなど）',
                'slug' => 'health-food',
                'description' => '健康食品（オーガニックスナック、フルーツバーなど）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 20,
            ],

            [
                'name' => '映画・音楽（DVD、CD、ストリーミングサービスなど）',
                'slug' => 'movie',
                'description' => '映画・音楽（DVD、CD、ストリーミングサービスなど）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 21,
            ],
            [
                'name' => 'ブック・コミック',
                'slug' => 'book',
                'description' => 'ブック・コミック',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 21,
            ],
            [
                'name' => 'キャラクターグッズ（マーチャンダイズ）',
                'slug' => 'merchandise',
                'description' => 'キャラクターグッズ（マーチャンダイズ）',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 21,
            ],

            [
                'name' => 'ボディスーツ・ロンパース',
                'slug' => 'bodysuit',
                'description' => 'ボディスーツ・ロンパース',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 22,
            ],
            [
                'name' => 'パジャマ・スリープウェア',
                'slug' => 'pajama',
                'description' => 'パジャマ・スリープウェア',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 22,
            ],
            [
                'name' => '帽子・手袋・靴下',
                'slug' => 'hat',
                'description' => '帽子・手袋・靴下',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 22,
            ],
            [
                'name' => 'アウター（ジャケット、コート、ブランケットなど）',
                'slug' => 'outer',
                'description' => 'アウター（ジャケット、コート、ブランケットなど）',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 22,
            ],

            [
                'name' => '哺乳瓶・乳首',
                'slug' => 'bottle',
                'description' => '哺乳瓶・乳首',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 23,
            ],
            [
                'name' => 'スプーン・フォーク',
                'slug' => 'spoon',
                'description' => 'スプーン・フォーク',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 23,
            ],
            [
                'name' => 'ベビーフード・おやつ',
                'slug' => 'food-snack',
                'description' => 'ベビーフード・おやつ',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 23,
            ],
            [
                'name' => '離乳食セット',
                'slug' => 'food-set',
                'description' => '離乳食セット',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 23,
            ],
            [
                'name' => 'ベビーシート・ハイチェア',
                'slug' => 'baby-seat',
                'description' => 'ベビーシート・ハイチェア',
                'image' => '',
                'sort' => 5,
                'sub_category_id' => 23,
            ],

            [
                'name' => 'おむつ・おしりふき',
                'slug' => 'diaper',
                'description' => 'おむつ・おしりふき',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 24,
            ],
            [
                'name' => 'ベビーバス・洗面具',
                'slug' => 'bath',
                'description' => 'ベビーバス・洗面具',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 24,
            ],
            [
                'name' => 'よだれかけ・ビブ',
                'slug' => 'bib',
                'description' => 'よだれかけ・ビブ',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 24,
            ],
            [
                'name' => '乳歯ケア用品',
                'slug' => 'tooth',
                'description' => '乳歯ケア用品',
                'image' => '',
                'sort' => 4,
                'sub_category_id' => 24,
            ],

            [
                'name' => 'ベビーカー・ベビーキャリー',
                'slug' => 'stroller',
                'description' => 'ベビーカー・ベビーキャリー',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 25,
            ],
            [
                'name' => 'チャイルドシート（車用）',
                'slug' => 'child-seat',
                'description' => 'チャイルドシート（車用）',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 25,
            ],
            [
                'name' => 'ベビーベッド・クレードル',
                'slug' => 'bed',
                'description' => 'ベビーベッド・クレードル',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 25,
            ],

            [
                'name' => 'オムツ替えマット',
                'slug' => 'diaper-mat',
                'description' => 'オムツ替えマット',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 26,
            ],
            [
                'name' => 'トレーニングパンツ',
                'slug' => 'training-pants',
                'description' => 'トレーニングパンツ',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 26,
            ],
            [
                'name' => 'ポティ・便座',
                'slug' => 'poty',
                'description' => 'ポティ・便座',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 26,
            ],

            [
                'name' => '教育的なおもちゃ（ラトル、積み木、布の本など）',
                'slug' => 'toy',
                'description' => '教育的なおもちゃ（ラトル、積み木、布の本など）',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 27,
            ],
            [
                'name' => 'プレイマット・プレイジム',
                'slug' => 'playmat',
                'description' => 'プレイマット・プレイジム',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 27,
            ],
            [
                'name' => '絵本・音楽',
                'slug' => 'playmat',
                'description' => '絵本・音楽',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 27,
            ],

            [
                'name' => 'ベビーモニター',
                'slug' => 'baby-monitor',
                'description' => 'ベビーモニター',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 28,
            ],
            [
                'name' => '安全ゲート・フェンス',
                'slug' => 'safety-gate',
                'description' => '安全ゲート・フェンス',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 28,
            ],
            [
                'name' => 'コーナー・エッジ保護',
                'slug' => 'corner',
                'description' => 'コーナー・エッジ保護',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 28,
            ],

            [
                'name' => 'ベビーローション・クリーム',
                'slug' => 'lotion',
                'description' => 'ベビーローション・クリーム',
                'image' => '',
                'sort' => 1,
                'sub_category_id' => 29,
            ],
            [
                'name' => 'ベビーシャンプー・ボディウォッシュ',
                'slug' => 'shampoo',
                'description' => 'ベビーシャンプー・ボディウォッシュ',
                'image' => '',
                'sort' => 2,
                'sub_category_id' => 29,
            ],
            [
                'name' => 'おしりクリーム',
                'slug' => 'cream',
                'description' => 'おしりクリーム',
                'image' => '',
                'sort' => 3,
                'sub_category_id' => 29,
            ],
        ]);
    }
}
